# Milestone Project 1

# Tic tac toe Game

In [1]:
#We need to print a board.
from IPython.display import clear_output

In [2]:
board = [1,2,3,4,5,6,7,8,9]

In [3]:
def resetboard():
    for i in range(0,9):
        board[i] = i+1

In [4]:
def print_board():
    #clear_output()
    #main()
    import numpy as np
    myboard = np.asarray(board)
    myboard.shape = (3,3)
    print myboard

In [5]:
# Take in player input.

In [6]:
def input_marker():
    global board
    n =  input('Please input a number(1-9): ')
    if n >=1 and n <= 9:
        c = input('make an marker: ')
        board[n-1] = c
        #print board
        print_board()
        
    '''
    for y in board:
        if n == y:
            c = input('make an marker: ')
            board[n-1] = c
            #print board
            print_board()
            #print
    '''


In [7]:
def main():
    #clear_output()
    print ' *** Welcome to play Tic Tac Toe Game ***'
    print
    print '                     Written by HooeyPooey'
    print
    print "Player1: 'o'         Player2: 'x'"
    print
    #show_board  =  print_board()

In [8]:
#Check if the game is won,tied, lost, or ongoing.

In [9]:
def check():
    b = board
    if (b[0] == b[1] == b[2] == 'o' or b[3] == b[4] == b[5] == 'o' or b[6] == b[7] == b[8] == 'o' or
        b[0] == b[3] == b[6]== 'o' or b[1] == b[4] == b[7] == 'o' or b[2] == b[5] == b[8] == 'o' or
        b[0] == b[4] == b[8] == 'o' or b[2] == b[4] == b[6] == 'o'):
        print 'player 1 win!'
        print "Please input 'c' for new game, input any key for exit"
        a = input('New game: ')
        if a == 'c':
            clear_output()
            resetboard()
            main()

    elif(b[0] == b[1] == b[2] == 'x' or b[3] == b[4] == b[5] == 'x' or b[6] == b[7] == b[8] == 'x' or
         b[0] == b[3] == b[6] == 'x' or b[1] == b[4] == b[7] == 'x' or b[2] == b[5] == b[8] == 'x' or
         b[0] == b[4] == b[8] == 'x' or b[2] == b[4] == b[6] == 'x'):
        print 'player 2 win!'
        print "Please input 'c' for new game, input any key for exit"
        a = input('New game: ')
        if a == 'c':
            clear_output()
            resetboard()
            main()

    else:
        #set() is unique ~ 
        if set(board) == {'x','o'}:
            print 'This is tie!'
            print "Please input 'c' for new game, input any key for exit"
            a = input('New game: ')
            if a == 'c':
                clear_output()
                resetboard()
                main()
            else:
                pass                

In [ ]:
# write a main function to start the game

In [ ]:

if __name__== "__main__":
    
    #main()
    print_board()
    while set(board) != {'x','o'}:
        print
        print 'next player: '
        mark_board  =  input_marker()
        mark_check  =  check()
        

 *** Welcome to play Tic Tac Toe Game ***

                     Written by HooeyPooey

Player1: 'o'         Player2: 'x'

[[1 2 3]
 [4 5 6]
 [7 8 9]]

next player: 
Please input a number(1-9): 1
make an marker: 'x'
[['x' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]

next player: 
Please input a number(1-9): 2
make an marker: 'o'
[['x' 'o' '3']
 ['4' '5' '6']
 ['7' '8' '9']]

next player: 
